version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8677:8677"
    environment:
      - PORT=8677
      - CHOKIDAR_USEPOLLING=true # Helps with hot reloading in some environments
    volumes:
      - ./frontend:/app  # Mount the local frontend directory to /app in the container
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5081:5081"

  proxy:
    image: nginx
    depends_on:
      - backend
      - db
      - frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5011:80

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5455:5455"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5455"
    command: -p 5455
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: gambit

volumes:
  postgres-data: # This named volume will persist your database data
