version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - CHOKIDAR_USEPOLLING=true # Helps with hot reloading in some environments
    volumes:
      - ./frontend:/app  # Mount the local frontend directory to /app in the container
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3001:3001"

  proxy:
    image: nginx
    depends_on:
      - backend
      - db
      - frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: gambit

volumes:
  postgres-data: # This named volume will persist your database data
